`timescale 1ns/1ps

`include "common/clk_util.sv"

// INT-mode power + correctness bench for the unchanged SC array: comparator-
// native spatial Booth (CNSB, sweeps/int_mode/model_red_team_novel.py).
//
// No hardware is changed.  The proposed INT preset gate is modelled by holding
// rng_en = 0 and forcing the two Sobol banks' random-value nets (the outputs of
// every sobol_generator, i.e. the flop outputs, upstream of every buffered copy
// that reaches the comparators) to the CNSB constants read from
// INT_PRESET_FILE.  With those thresholds the unchanged comparators turn a
// per-lane 8-bit code into the Booth 2x8 thermometer, so lane k of tile (h, v)
// counts |da|*|dw| <= 16 and its sign is a_sign ^ w_sign.
//
// Every clock the bench drives a new slice on the existing ports (codes on
// a/w_binary_in, digit signs on a/w_signs_in), with load_a/load_w/load_a_sign/
// load_w_sign held high, from INT_STIM_FILE (one 1152-bit word per slice,
// {w_signs, w_binary, a_signs, a_binary}; generated by
// sweeps/int_mode/cnsb_booth_energy.py gen).  Slice s is captured by the
// peripheral at edge s+1, by the PE bit/sign pipes at s+2 and accumulated at
// s+3.  mac_en covers INT_SLICES accumulating edges; the file holds two more
// slices so the peripheral and the PE pipes carry real data on every edge of
// the SAIF window (steady state, no pipeline fill or drain inside it).
//
// After the window the accumulators are drained exactly as in
// power_payn_array.sv (drain outside the SAIF window) and written to
// INT_TRACE_FILE; sweeps/int_mode/cnsb_booth_energy.py check compares every
// tile to an independent T_pq reference and the edge combine to numpy A @ W.
// Inputs launch at the negedge; mac_en rises just after a posedge, as in the
// SC bench, for setup margin on the shared acc_low clock gate.

`ifndef GL_SIM
`ifndef PAYN_ARRAY_EXTERNAL_RTL
`include "payn/payn_array.sv"
`endif
`endif

`ifndef PAYN_ARRAY_DUT
`define PAYN_ARRAY_DUT payn_array
`endif
`ifndef SC_K
`define SC_K 8
`endif
`ifndef SC_M
`define SC_M 16
`endif
`ifndef SC_NH
`define SC_NH 8
`endif
`ifndef SC_NW
`define SC_NW 8
`endif
`ifndef SC_WIDTH
`define SC_WIDTH 8
`endif
`ifndef SC_OWIDTH
`define SC_OWIDTH 24
`endif
`ifndef INT_SLICES
`define INT_SLICES 3072
`endif
`ifndef INT_STIM_FILE
`define INT_STIM_FILE "int_stim.mem"
`endif
`ifndef INT_PRESET_FILE
`define INT_PRESET_FILE "int_preset.mem"
`endif
`ifndef INT_TRACE_FILE
`define INT_TRACE_FILE "int_booth_trace.txt"
`endif
`ifndef ASTRAEA_CLK_PERIOD_NS
`define ASTRAEA_CLK_PERIOD_NS 2.5
`endif

module Top;
    localparam int K = `SC_K;
    localparam int M = `SC_M;
    localparam int N_H = `SC_NH;
    localparam int N_W = `SC_NW;
    localparam int WIDTH = `SC_WIDTH;
    localparam int OWIDTH = `SC_OWIDTH;
    localparam int N_SLICES = `INT_SLICES;
    localparam int N_STIM = N_SLICES + 2;
    localparam int A_BW = N_H*K*WIDTH;
    localparam int A_SW = N_H*K;
    localparam int W_BW = N_W*K*WIDTH;
    localparam int W_SW = N_W*K;
    localparam int STIM_W = A_BW + A_SW + W_BW + W_SW;
    localparam real PERIOD = `ASTRAEA_CLK_PERIOD_NS;

    logic clk, reset, timeout;
    logic rng_en = 1'b0, mac_en = 1'b0, shift_in = 1'b0;
    logic load_a = 1'b0, load_w = 1'b0, load_a_sign = 1'b0, load_w_sign = 1'b0;

    logic [A_BW-1:0]        a_binary_in = '0;
    logic [A_SW-1:0]        a_signs_in = '0;
    logic [W_BW-1:0]        w_binary_in = '0;
    logic [W_SW-1:0]        w_signs_in = '0;
    logic [N_H*OWIDTH-1:0]  acc_in_west = '0;
    logic [N_H*OWIDTH-1:0]  acc_out_east;

    logic [STIM_W-1:0] stim_mem [N_STIM];
    logic [M*WIDTH-1:0] preset_mem [2];
    logic [M*WIDTH-1:0] preset_a, preset_w;

    integer signed drain [N_H][N_W];
    integer trace_file;
    bit monitor_x = 1'b0;

    ClkUtils #(.TIMEOUT(N_STIM + N_W + 256)) clk_utils (
        .clk, .reset, .timeout
    );

    always @(acc_out_east)
        if (monitor_x && $isunknown(acc_out_east))
            $fatal(1, "[X-FAIL] drain rail entered X during SAIF: %h", acc_out_east);

    `PAYN_ARRAY_DUT #(
        .K(K), .M(M), .N_H(N_H), .N_W(N_W), .WIDTH(WIDTH), .OWIDTH(OWIDTH)
    ) dut (.*);

`ifdef GL_SIM
    initial begin
`ifndef NO_SDF
`ifdef SDF_FILE
        $display("[INFO] $sdf_annotate(`SDF_FILE, dut)");
        $sdf_annotate(`SDF_FILE, dut);
`endif
`endif
    end
`endif

    // ---- INT preset: hold both Sobol banks' random values at the constants ----
    initial begin
        $readmemh(`INT_PRESET_FILE, preset_mem);
        if ($isunknown(preset_mem[0]) || $isunknown(preset_mem[1]))
            $fatal(1, "cannot read %s", `INT_PRESET_FILE);
        preset_a = preset_mem[0];
        preset_w = preset_mem[1];
    end

`ifdef GL_SIM
    // Mapped netlist: force each generator's random_value net (flop outputs).
    // All buffered copies (FE_OFN*/p* ports) are driven from these nets.
`define INT_FORCE_LANE(bank, lane, value) \
    initial force dut.bank.g_lane_``lane``__u_generator.random_value = value[lane*8 +: 8];
    `INT_FORCE_LANE(u_a_rng, 0, preset_a)
    `INT_FORCE_LANE(u_a_rng, 1, preset_a)
    `INT_FORCE_LANE(u_a_rng, 2, preset_a)
    `INT_FORCE_LANE(u_a_rng, 3, preset_a)
    `INT_FORCE_LANE(u_a_rng, 4, preset_a)
    `INT_FORCE_LANE(u_a_rng, 5, preset_a)
    `INT_FORCE_LANE(u_a_rng, 6, preset_a)
    `INT_FORCE_LANE(u_a_rng, 7, preset_a)
    `INT_FORCE_LANE(u_a_rng, 8, preset_a)
    `INT_FORCE_LANE(u_a_rng, 9, preset_a)
    `INT_FORCE_LANE(u_a_rng, 10, preset_a)
    `INT_FORCE_LANE(u_a_rng, 11, preset_a)
    `INT_FORCE_LANE(u_a_rng, 12, preset_a)
    `INT_FORCE_LANE(u_a_rng, 13, preset_a)
    `INT_FORCE_LANE(u_a_rng, 14, preset_a)
    `INT_FORCE_LANE(u_a_rng, 15, preset_a)
    `INT_FORCE_LANE(u_w_rng, 0, preset_w)
    `INT_FORCE_LANE(u_w_rng, 1, preset_w)
    `INT_FORCE_LANE(u_w_rng, 2, preset_w)
    `INT_FORCE_LANE(u_w_rng, 3, preset_w)
    `INT_FORCE_LANE(u_w_rng, 4, preset_w)
    `INT_FORCE_LANE(u_w_rng, 5, preset_w)
    `INT_FORCE_LANE(u_w_rng, 6, preset_w)
    `INT_FORCE_LANE(u_w_rng, 7, preset_w)
    `INT_FORCE_LANE(u_w_rng, 8, preset_w)
    `INT_FORCE_LANE(u_w_rng, 9, preset_w)
    `INT_FORCE_LANE(u_w_rng, 10, preset_w)
    `INT_FORCE_LANE(u_w_rng, 11, preset_w)
    `INT_FORCE_LANE(u_w_rng, 12, preset_w)
    `INT_FORCE_LANE(u_w_rng, 13, preset_w)
    `INT_FORCE_LANE(u_w_rng, 14, preset_w)
    `INT_FORCE_LANE(u_w_rng, 15, preset_w)
`undef INT_FORCE_LANE
`else
    // RTL: the peripheral reads the top-level random-value buses directly.
    initial force dut.a_random_values = preset_a;
    initial force dut.w_random_values = preset_w;
`endif

    task automatic apply_slice(input int i);
        {w_signs_in, w_binary_in, a_signs_in, a_binary_in} = stim_mem[i];
    endtask

    initial begin
        assert (N_SLICES > 0) else $fatal(1, "INT_SLICES must be positive");
        $readmemh(`INT_STIM_FILE, stim_mem);
        for (int i = 0; i < N_STIM; i++)
            if ($isunknown(stim_mem[i]))
                $fatal(1, "%s: slice %0d missing or unknown (need %0d slices)",
                       `INT_STIM_FILE, i, N_STIM);

        clk_utils.set_clock(PERIOD);
        clk_utils.do_reset();
        repeat (2) @(negedge clk);

        trace_file = $fopen(`INT_TRACE_FILE, "w");
        assert (trace_file != 0) else $fatal(1, "cannot open %s", `INT_TRACE_FILE);
        $fwrite(trace_file, "INTCFG %0d %0d %0d %0d %0d %0d %0d\n",
                K, M, N_H, N_W, WIDTH, OWIDTH, N_SLICES);
        $fwrite(trace_file, "PRESET_A %h\nPRESET_W %h\n", preset_a, preset_w);

        // Loads stay high for the whole INT run: every clock is a new slice.
        apply_slice(0);
        load_a = 1'b1;
        load_w = 1'b1;
        load_a_sign = 1'b1;
        load_w_sign = 1'b1;
        @(posedge clk);            // edge 1: peripheral captures slice 0
        @(negedge clk);
        apply_slice(1);
        @(posedge clk);            // edge 2: PE pipes capture slice 0
        mac_en = 1'b1;             // first accumulating edge is edge 3
        @(negedge clk);
        apply_slice(2);

        // ---- SAIF window: N_SLICES accumulating edges, all stages busy ----
`ifdef GL_SIM
        $set_gate_level_monitoring("rtl_on");
`else
        $set_gate_level_monitoring("rtl_on", "sv");
`endif
        $set_toggle_region(dut);
        monitor_x = 1'b1;
        $toggle_start;
        for (int cycle = 0; cycle < N_SLICES; cycle++) begin
            @(posedge clk);        // edge 3+cycle accumulates slice `cycle`
            @(negedge clk);
            if (cycle + 3 < N_STIM)
                apply_slice(cycle + 3);
        end
        mac_en = 1'b0;
        #1ps;
        $toggle_stop;
        monitor_x = 1'b0;
        $toggle_report("dut.saif", 1.0e-12, "Top.dut");

        load_a = 1'b0;
        load_w = 1'b0;
        load_a_sign = 1'b0;
        load_w_sign = 1'b0;
        a_binary_in = '0;
        a_signs_in = '0;
        w_binary_in = '0;
        w_signs_in = '0;

        // ---- drain outside SAIF, identical to power_payn_array.sv ----
        acc_in_west = '0;
        shift_in = 1'b1;
        for (int s = 0; s < N_W; s++) begin
            @(posedge clk);
            for (int h = 0; h < N_H; h++)
                drain[h][N_W-1-s] = $signed(acc_out_east[h*OWIDTH +: OWIDTH]);
            @(negedge clk);
        end
        shift_in = 1'b0;
        for (int h = 0; h < N_H; h++)
            for (int v = 0; v < N_W; v++)
                if ($isunknown(drain[h][v]))
                    $fatal(1, "[X-FAIL] drained tile (%0d,%0d) is X", h, v);

        $fwrite(trace_file, "DRAIN");
        for (int h = 0; h < N_H; h++)
            for (int v = 0; v < N_W; v++) $fwrite(trace_file, " %0d", drain[h][v]);
        $fwrite(trace_file, "\nTRACE_END\n");
        $fclose(trace_file);

        $display("PASS: INT Booth SAIF captured; %0d slices, drain dumped -> cnsb_booth_energy.py check",
                 N_SLICES);
        $finish;
    end
endmodule
