#!/bin/bash
# Unary-rate 8x8 baseline.
export TOP=array_8
export TECH=TSMC22
export SRC_SV="baselines/unary_rate/array_8.sv"
export PERIOD=2.5
export MULTIBIT_INFER=1
export CLOCK_GATE=1
export RTL_PREFLIGHT_CMD="make --no-print-directory sim GL= TARGET= TOP=Top TB=designs/baselines/unary_rate/tb/test_array_8.sv BUILD_DIR=build/rtl_preflight/ur_array"
