#!/usr/bin/env python3
"""Generate synthesizable RTL for the CNSB INT-mode edge blocks that the
round-1 proposals only hand-estimated, plus self-checking test vectors.

Blocks (one instance each, as instantiated per edge half / per PE row):
  cnsb_feed_r4_half    A side, radix-4 Booth recoder for 2 activations x 8 lanes
                       -> 8 tile rows x 8 lanes of 8-bit comparator codes + digit
                       signs, plus the 576-bit SC/INT port-source mux.  INT4 cut.
  cnsb_feed_r16_half   W side, radix-16 Booth |digit| + per-lane 9-entry code
                       table for 4 weights x 8 lanes -> 8 tile columns, plus the
                       576-bit port mux.  W4 cut.  Two code choices: _hi (gap top,
                       red_team) and _lo (gap bottom + 1, spatial).
  cnsb_combiner_row_1st / _2st
                       east-edge combiner for one PE row (8 x 24-bit drain rails):
                       INT8 s_i = T0+4T1+16T2+64T3 and the q-pair Horner 16H+s,
                       W4A8 (s_i), INT4 (T0+4T1, 4 outputs).  _2st registers the
                       rails first (timing-safe), _1st does not.
  sobol_pair_preset    copy of the shared Sobol pair with a synchronous INT preset
                       (compare against sobol_pair_orig = the unmodified RTL).

Presets / code tables use the red_team 'r4rows' preset (row bank = A, salt 0;
column bank = W, salt 128), the orientation both proposals use for 1x1 and 4x4.
"""
from __future__ import annotations

import random
from pathlib import Path

OUT = Path(__file__).resolve().parent / "rtl"
VEC = Path(__file__).resolve().parent / "vectors"
K, M = 8, 16
SK, SM = 159, 99           # re-derived from pe_peripheral.sv in cnsb_cost_realism.py
SALT_A, SALT_W = 0, 128
ROW = [184, 112, 109, 173, 159, 27, 142, 93, 253, 44, 148, 40, 250, 207, 155, 139]
COL = [243, 203, 204, 246, 229, 147, 152, 9, 146, 95, 190, 181, 96, 91, 75, 37]


def thr(r, salt):
    return [[r[m] ^ ((k * SK + m * SM + salt) & 255) for m in range(M)] for k in range(K)]


TA, TW = thr(ROW, SALT_A), thr(COL, SALT_W)


def codes(t, n, choice):
    s = sorted(t)
    step = 16 // (n - 1)
    c = [0]
    for x in range(1, n - 1):
        lo, hi = s[step * x - 1], s[step * x]
        assert lo < hi
        c.append(hi if choice == "hi" else lo + 1)
    c.append(255)
    return c


def certify(cr_all, cw_all):
    for k in range(K):
        for x in range(3):
            for y in range(9):
                cnt = sum((cr_all[k][x] > TA[k][m]) and (cw_all[k][y] > TW[k][m])
                          for m in range(M))
                assert cnt == x * y, (k, x, y, cnt)


CR = {ch: [codes(TA[k], 3, ch) for k in range(K)] for ch in ("hi", "lo")}
CW = {ch: [codes(TW[k], 9, ch) for k in range(K)] for ch in ("hi", "lo")}
for ch in ("hi", "lo"):
    certify(CR[ch], CW[ch])


# --------------------------------------------------------------- RTL text --
def feed_r4(choice="hi"):
    c1 = [CR[choice][k][1] for k in range(K)]
    c1_init = ", ".join(f"8'd{v}" for v in c1)
    return f"""// Generated by sweeps/int_mode/verify/gen_cnsb_rtl.py -- do not edit.
// CNSB A-side (radix-4) feeder for one edge half: 2 activations x 8 lanes of raw
// INT8 (or 2 x INT4 packed per byte) -> 8 tile rows (h = 4i+p) x 8 lanes of
// comparator codes {{0, C1[k], 255}} and digit signs, muxed with the SC port.
module cnsb_feed_r4_half (
    input  logic         clk,          // timing reference only (combinational block)
    input  logic         int_en,
    input  logic         int4,
    input  logic [127:0] raw,          // byte (i,k) at [(i*8+k)*8 +: 8]
    input  logic [511:0] sc_mag,
    input  logic [63:0]  sc_sign,
    output logic [511:0] port_mag,
    output logic [63:0]  port_sign
);
    localparam logic [7:0] C1 [8] = '{{{c1_init}}};
    for (genvar i = 0; i < 2; i++) begin : g_i
        for (genvar p = 0; p < 4; p++) begin : g_p
            for (genvar k = 0; k < 8; k++) begin : g_k
                localparam int H = 4*i + p;
                logic [7:0] b;
                logic hi, mid, lo, x1, x0, nz, two;
                logic [7:0] code;
                assign b   = raw[(i*8 + k)*8 +: 8];
                assign hi  = b[2*p + 1];
                assign mid = b[2*p];
                if (p == 0) begin : g_p0
                    assign lo = 1'b0;
                end else if (p == 2) begin : g_p2
                    assign lo = b[2*p - 1] & ~int4;
                end else begin : g_pn
                    assign lo = b[2*p - 1];
                end
                assign x1  = hi ^ mid;
                assign x0  = mid ^ lo;
                assign nz  = x1 | x0;
                assign two = x1 & ~x0;
                for (genvar j = 0; j < 8; j++) begin : g_bit
                    assign code[j] = C1[k][j] ? nz : two;
                end
                assign port_mag[(H*8 + k)*8 +: 8] = int_en ? code : sc_mag[(H*8 + k)*8 +: 8];
                assign port_sign[H*8 + k] = int_en ? hi : sc_sign[H*8 + k];
            end
        end
    end
endmodule
"""


def feed_r16(choice):
    rows = []
    for k in range(K):
        rows.append("'{" + ", ".join(f"8'd{v}" for v in CW[choice][k]) + "}")
    tab = ",\n        ".join(rows)
    return f"""// Generated by sweeps/int_mode/verify/gen_cnsb_rtl.py -- do not edit.
// CNSB W-side (radix-16) feeder for one edge half, code choice '{choice}':
// 4 weights x 8 lanes of raw INT8 (or 2 x W4 per byte) -> 8 tile columns
// (v = 2j+q) x 8 lanes of per-lane comparator codes E[k][|d|] and digit signs,
// muxed with the SC port.
module cnsb_feed_r16_half_{choice} (
    input  logic         clk,          // timing reference only (combinational block)
    input  logic         int_en,
    input  logic         w4,
    input  logic [255:0] raw,          // byte (j,k) at [(j*8+k)*8 +: 8]
    input  logic [511:0] sc_mag,
    input  logic [63:0]  sc_sign,
    output logic [511:0] port_mag,
    output logic [63:0]  port_sign
);
    localparam logic [7:0] E [8][9] = '{{
        {tab}
    }};
    for (genvar j = 0; j < 4; j++) begin : g_j
        for (genvar q = 0; q < 2; q++) begin : g_q
            for (genvar k = 0; k < 8; k++) begin : g_k
                localparam int V = 2*j + q;
                logic [7:0] b;
                logic b3, bm1;
                logic [3:0] u, mag;
                logic [7:0] code;
                assign b  = raw[(j*8 + k)*8 +: 8];
                assign b3 = b[4*q + 3];
                if (q == 0) begin : g_q0
                    assign bm1 = 1'b0;
                end else begin : g_q1
                    assign bm1 = b[3] & ~w4;
                end
                assign u   = {{1'b0, b[4*q + 2 -: 3]}} + {{3'b0, bm1}};
                assign mag = b3 ? (4'd8 - u) : u;
                always_comb begin
                    case (mag)
                        4'd0: code = E[k][0];
                        4'd1: code = E[k][1];
                        4'd2: code = E[k][2];
                        4'd3: code = E[k][3];
                        4'd4: code = E[k][4];
                        4'd5: code = E[k][5];
                        4'd6: code = E[k][6];
                        4'd7: code = E[k][7];
                        4'd8: code = E[k][8];
                        default: code = 'x;
                    endcase
                end
                assign port_mag[(V*8 + k)*8 +: 8] = int_en ? code : sc_mag[(V*8 + k)*8 +: 8];
                assign port_sign[V*8 + k] = int_en ? b3 : sc_sign[V*8 + k];
            end
        end
    end
endmodule
"""


def combiner(two_stage):
    name = "cnsb_combiner_row_2st" if two_stage else "cnsb_combiner_row_1st"
    if two_stage:
        front = """    logic signed [23:0] t [8];
    logic [1:0] mode_q;
    logic q1_q, drain_q;
    always_ff @(posedge clk) begin
        for (int h = 0; h < 8; h++) t[h] <= acc[h*24 +: 24];
        mode_q  <= mode;
        q1_q    <= q1;
        drain_q <= drain;
    end
"""
    else:
        front = """    logic signed [23:0] t [8];
    logic [1:0] mode_q;
    logic q1_q, drain_q;
    always_comb begin
        for (int h = 0; h < 8; h++) t[h] = acc[h*24 +: 24];
        mode_q  = mode;
        q1_q    = q1;
        drain_q = drain;
    end
"""
    return f"""// Generated by sweeps/int_mode/verify/gen_cnsb_rtl.py -- do not edit.
// CNSB east-edge combiner for one PE row: 8 x 24-bit drain rails per cycle.
//   mode 0 INT8 : s_i = T[4i] + 4T[4i+1] + 16T[4i+2] + 64T[4i+3]; on q1 H_i <= s_i,
//                 else out_i <= 16*H_i + s_i  (2 outputs every 2 drain cycles)
//   mode 1 W4A8 : out_i <= s_i                (2 outputs per drain cycle)
//   mode 2 INT4 : out_g <= T[2g] + 4T[2g+1]   (4 outputs per drain cycle)
module {name} (
    input  logic        clk,
    input  logic [1:0]  mode,
    input  logic        q1,
    input  logic        drain,
    input  logic [191:0] acc,
    output logic [143:0] out,          // 4 x 36-bit signed
    output logic        out_valid
);
{front}
    logic signed [35:0] s [2];
    logic signed [35:0] p [4];
    logic signed [35:0] h [2];
    always_comb begin
        for (int g = 0; g < 4; g++)
            p[g] = 36'(t[2*g]) + (36'(t[2*g+1]) <<< 2);
        for (int i = 0; i < 2; i++)
            s[i] = p[2*i] + (p[2*i+1] <<< 4);
    end
    always_ff @(posedge clk) begin
        out_valid <= 1'b0;
        if (drain_q) begin
            case (mode_q)
                2'd0: begin
                    if (q1_q) begin
                        h[0] <= s[0];
                        h[1] <= s[1];
                    end else begin
                        out[0 +: 36]  <= (h[0] <<< 4) + s[0];
                        out[36 +: 36] <= (h[1] <<< 4) + s[1];
                        out_valid <= 1'b1;
                    end
                end
                2'd1: begin
                    out[0 +: 36]  <= s[0];
                    out[36 +: 36] <= s[1];
                    out_valid <= 1'b1;
                end
                default: begin
                    for (int g = 0; g < 4; g++) out[g*36 +: 36] <= p[g];
                    out_valid <= 1'b1;
                end
            endcase
        end
    end
endmodule
"""


def sobol_preset():
    a_pre = ", ".join(f"8'd{v}" for v in ROW)
    w_pre = ", ".join(f"8'd{v}" for v in COL)
    return f"""// Generated by sweeps/int_mode/verify/gen_cnsb_rtl.py -- do not edit.
// The shared Sobol pair of payn_array_signed_segmented_csa with an INT-mode
// synchronous preset of every random_value register (count untouched).  The
// generator body is copied from designs/payn/sobol.sv; only the preset branch is
// new.  sobol_pair_orig instantiates the unmodified sobol_bank for comparison.
`include "payn/sobol.sv"

module sobol_generator_preset #(
    parameter int WIDTH = 8,
    parameter int DIRECTION_SET = 0,
    parameter logic [WIDTH-1:0] DIGITAL_SHIFT = '0,
    parameter logic [WIDTH-1:0] PRESET = '0
) (
    input logic clk, input logic reset, input logic enable, input logic preset,
    output logic [WIDTH-1:0] random_value
);
    logic [WIDTH-1:0] count, selected_direction;
    logic direction_found;
    function automatic logic [WIDTH-1:0] direction_vector(input int index);
        logic [7:0] dv;
        begin
            dv = '0;
            if (DIRECTION_SET == 0) begin
                direction_vector = '0;
                direction_vector[WIDTH-1-index] = 1'b1;
            end else begin
                case (index)
                    0: dv = 8'h80; 1: dv = 8'h40; 2: dv = 8'h20; 3: dv = 8'h10;
                    4: dv = 8'h48; 5: dv = 8'h04; 6: dv = 8'h52; 7: dv = 8'hff;
                    default: dv = '0;
                endcase
                direction_vector = WIDTH'(dv);
            end
        end
    endfunction
    always_comb begin
        selected_direction = '0;
        direction_found = 1'b0;
        for (int index = 0; index < WIDTH; index++)
            if (!direction_found && !count[index]) begin
                selected_direction = direction_vector(index);
                direction_found = 1'b1;
            end
    end
    always_ff @(posedge clk or posedge reset) begin
        if (reset) begin
            count <= '0;
            random_value <= DIGITAL_SHIFT;
        end else if (preset) begin
            random_value <= PRESET;
        end else if (enable) begin
            count <= count + 1'b1;
            random_value <= random_value ^ selected_direction;
        end
    end
endmodule

module sobol_pair_preset (
    input logic clk, input logic reset, input logic rng_en, input logic preset,
    output logic [127:0] a_random_values, output logic [127:0] w_random_values
);
    localparam logic [7:0] PA [16] = '{{{a_pre}}};
    localparam logic [7:0] PW [16] = '{{{w_pre}}};
    for (genvar m = 0; m < 16; m++) begin : g_lane
        sobol_generator_preset #(.WIDTH(8), .DIRECTION_SET(0),
            .DIGITAL_SHIFT(8'h17 ^ 8'(8'h53 * m)), .PRESET(PA[m])) u_a (
            .clk, .reset, .enable(rng_en), .preset, .random_value(a_random_values[m*8 +: 8]));
        sobol_generator_preset #(.WIDTH(8), .DIRECTION_SET(1),
            .DIGITAL_SHIFT(8'h9d ^ 8'(8'h2b * m)), .PRESET(PW[m])) u_w (
            .clk, .reset, .enable(rng_en), .preset, .random_value(w_random_values[m*8 +: 8]));
    end
endmodule

module sobol_pair_orig (
    input logic clk, input logic reset, input logic rng_en,
    output logic [127:0] a_random_values, output logic [127:0] w_random_values
);
    sobol_bank #(.WIDTH(8), .M(16), .DIRECTION_SET(0), .DIGITAL_SHIFT_BASE(8'h17),
                 .DIGITAL_SHIFT_STRIDE(8'h53), .FULL_PERIOD_WRAP(1'b0)) u_a_rng (
        .clk, .reset, .enable(rng_en), .random_values(a_random_values));
    sobol_bank #(.WIDTH(8), .M(16), .DIRECTION_SET(1), .DIGITAL_SHIFT_BASE(8'h9d),
                 .DIGITAL_SHIFT_STRIDE(8'h2b), .FULL_PERIOD_WRAP(1'b0)) u_w_rng (
        .clk, .reset, .enable(rng_en), .random_values(w_random_values));
endmodule
"""


# ------------------------------------------------------- reference models --
def bit(x, i):
    return (x >> i) & 1 if i >= 0 else 0


def ref_r4(int_en, int4, raw, sc_mag, sc_sign, choice="hi"):
    mag, sgn = [0] * 64, [0] * 64
    for i in range(2):
        for p in range(4):
            for k in range(8):
                h = 4 * i + p
                b = (raw >> ((i * 8 + k) * 8)) & 255
                hi, mid = bit(b, 2 * p + 1), bit(b, 2 * p)
                lo = 0 if p == 0 else (bit(b, 2 * p - 1) & (0 if (p == 2 and int4) else 1))
                d = -2 * hi + mid + lo
                code = CR[choice][k][abs(d)]
                idx = h * 8 + k
                mag[idx] = code if int_en else (sc_mag >> (idx * 8)) & 255
                sgn[idx] = hi if int_en else (sc_sign >> idx) & 1
    return sum(v << (8 * n) for n, v in enumerate(mag)), sum(v << n for n, v in enumerate(sgn))


def ref_r16(int_en, w4, raw, sc_mag, sc_sign, choice):
    mag, sgn = [0] * 64, [0] * 64
    for j in range(4):
        for q in range(2):
            for k in range(8):
                v = 2 * j + q
                b = (raw >> ((j * 8 + k) * 8)) & 255
                b3 = bit(b, 4 * q + 3)
                bm1 = 0 if q == 0 else (bit(b, 3) & (0 if w4 else 1))
                d = -8 * b3 + 4 * bit(b, 4 * q + 2) + 2 * bit(b, 4 * q + 1) + bit(b, 4 * q) + bm1
                idx = v * 8 + k
                mag[idx] = CW[choice][k][abs(d)] if int_en else (sc_mag >> (idx * 8)) & 255
                sgn[idx] = b3 if int_en else (sc_sign >> idx) & 1
    return sum(v << (8 * n) for n, v in enumerate(mag)), sum(v << n for n, v in enumerate(sgn))


def tc(v, w):
    return v & ((1 << w) - 1)


def main():
    OUT.mkdir(exist_ok=True)
    VEC.mkdir(exist_ok=True)
    (OUT / "cnsb_feed_r4_half.sv").write_text(feed_r4())
    for ch in ("hi", "lo"):
        (OUT / f"cnsb_feed_r16_half_{ch}.sv").write_text(feed_r16(ch))
    (OUT / "cnsb_combiner_row_1st.sv").write_text(combiner(False))
    (OUT / "cnsb_combiner_row_2st.sv").write_text(combiner(True))
    (OUT / "sobol_pair_preset.sv").write_text(sobol_preset())

    rng = random.Random(20261003)
    # feeder vectors: exhaustive digit coverage via random + all-byte sweeps
    n = 600
    with open(VEC / "feed_r4.hex", "w") as f4, open(VEC / "feed_r16_hi.hex", "w") as fh, \
            open(VEC / "feed_r16_lo.hex", "w") as fl:
        for t in range(n):
            int_en = 1 if t % 5 else 0
            mode4 = 1 if t % 3 == 0 else 0
            if t < 256:   # every byte value on every lane
                raw_a = sum(t << (8 * x) for x in range(16))
                raw_w = sum(t << (8 * x) for x in range(32))
            else:
                raw_a = rng.getrandbits(128)
                raw_w = rng.getrandbits(256)
            sc_mag, sc_sign = rng.getrandbits(512), rng.getrandbits(64)
            pm, ps = ref_r4(int_en, mode4, raw_a, sc_mag, sc_sign)
            f4.write(f"{int_en:x} {mode4:x} {raw_a:032x} {sc_mag:0128x} {sc_sign:016x} {pm:0128x} {ps:016x}\n")
            for ch, fobj in (("hi", fh), ("lo", fl)):
                pm, ps = ref_r16(int_en, mode4, raw_w, sc_mag, sc_sign, ch)
                fobj.write(f"{int_en:x} {mode4:x} {raw_w:064x} {sc_mag:0128x} {sc_sign:016x} {pm:0128x} {ps:016x}\n")
    # combiner vectors: one drain sequence per mode, cycle by cycle (1-stage
    # timing: inputs at cycle c -> outputs visible after the edge c)
    with open(VEC / "combiner.hex", "w") as fc:
        H = [0, 0]
        for t in range(400):
            mode = [0, 0, 0, 0, 1, 2][t % 6] if t > 40 else 0
            drain = 1 if (t % 7) != 6 else 0
            q1 = (1 - (t % 2)) if mode == 0 else 0
            T = [rng.randint(-(1 << 23), (1 << 23) - 1) for _ in range(8)]
            if t % 11 == 0:
                T = [-(1 << 23)] * 8
            if t % 13 == 0:
                T = [(1 << 23) - 1] * 8
            acc = sum(tc(T[h], 24) << (24 * h) for h in range(8))
            P = [T[2 * g] + 4 * T[2 * g + 1] for g in range(4)]
            S = [P[0] + 16 * P[1], P[2] + 16 * P[3]]
            valid, outs = 0, None
            if drain:
                if mode == 0:
                    if q1:
                        H = S[:]
                    else:
                        outs = [16 * H[0] + S[0], 16 * H[1] + S[1]]
                        valid = 1
                elif mode == 1:
                    outs, valid = S[:], 1
                else:
                    outs, valid = P[:], 1
            ov = 0
            mask = 0
            if valid:
                for g, o in enumerate(outs):
                    ov |= tc(o, 36) << (36 * g)
                    mask |= ((1 << 36) - 1) << (36 * g)
            fc.write(f"{mode:x} {q1:x} {drain:x} {acc:048x} {valid:x} {ov:036x} {mask:036x}\n")
    print("wrote RTL to", OUT, "and vectors to", VEC)
    for ch in ("hi", "lo"):
        print(f"  W codes ({ch}):", CW[ch])
        print(f"  A C1   ({ch}):", [CR[ch][k][1] for k in range(K)])


if __name__ == "__main__":
    main()
