#!/bin/bash
export TOP=binary_int8_mac_comb
export TECH=GF22FDX
export SRC_SV="baselines/soft_error/binary_int8_mac_comb.sv"
export PERIOD=1
export POST_LOAD_SCRIPT=../../../PaYN/syn/scripts/GF22_limit_cell_roc.tcl
export FLATTEN=1
: ${PROCESS_CORNER:=TT}
: ${VDD_CORNER:=0P80V}
: ${TEMP_CORNER:=25C}
export PROCESS_CORNER VDD_CORNER TEMP_CORNER
