#!/usr/bin/env python3
"""Mock Innovus database for a dry run of the SC pre-placement Tcl (pins + distribution guides) without Innovus.

Reads a synthesized netlist (the netlist APR starts from) and writes a Tcl file that
sweeps/cbsg/pin_dryrun/innovus_mock.tcl sources:
  MOCK_TERMS   every top-level port bit, bit-blasted as Innovus names its terms (bus[i], scalars plain);
  MOCK_CELLS   every instance name visible to get_cells with the hierarchical prefixes the scripts use:
               top-level instances, u_pe/<inst>, u_pe/u_array_core/<inst> (leaf cells and the tile instances);
  MOCK_DIE_UM  an estimated floorplan box: floorPlan -r 1 CORE_UTIL 10 10 10 10 (apr.tcl) on the synthesized
               cell area, i.e. side = sqrt(area / util) + 2 x 10 um (the PAYN_SC_CSA baseline gives 269.2 um vs the
               routed 270.06 x 268.52 um DIEAREA).

  python3 sweeps/cbsg/pin_dryrun/netlist_mockdb.py SYN_RUN_DIR TOP OUT.tcl [--util 0.70]
"""
import argparse
import math
import re
from pathlib import Path


def modules(text):
    out = {}
    for m in re.finditer(r'^\s*module\s+(\S+)\s*\(', text, re.M):
        out[m[1]] = text[m.start():text.index('endmodule', m.start())]
    return out


def instances(body):
    # "  CELLTYPE NAME ( .pin(...) ..." -- names may be escaped identifiers
    return [(m[1], m[2]) for m in re.finditer(r'^\s*(\S+)\s+(\\\S+|\S+)\s*\(\s*\.', body, re.M)
            if m[1] not in ('module', 'input', 'output', 'inout', 'wire', 'assign')]


def tcl_word(s):
    return '{' + s + '}' if not re.search(r'[{}\\\s]', s) else '"' + s.replace('\\', '\\\\').replace('"', '\\"') \
        .replace('[', '\\[').replace(']', '\\]').replace('$', '\\$') + '"'


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('syn_dir', type=Path)
    ap.add_argument('top')
    ap.add_argument('out', type=Path)
    ap.add_argument('--util', type=float, default=0.70)
    a = ap.parse_args()
    text = (a.syn_dir / f'{a.top}.syn.v').read_text()
    mods = modules(text)
    top = mods[a.top]
    terms = []
    for d in re.finditer(r'^\s*(input|output|inout)\s*(\[(\d+):(\d+)\])?\s*([^;]+);', top, re.M):
        for name in [x.strip() for x in d[5].split(',') if x.strip()]:
            if d[2]:
                hi, lo = int(d[3]), int(d[4])
                terms += [f'{name}[{i}]' for i in range(min(hi, lo), max(hi, lo) + 1)]
            else:
                terms.append(name)
    cells = []
    top_insts = instances(top)
    cells += [n.lstrip('\\') for _, n in top_insts]
    sub = {n: t for t, n in top_insts}
    pe_mod = sub.get('u_pe')
    core_mod = None
    if pe_mod in mods:
        pe_insts = instances(mods[pe_mod])
        cells += ['u_pe/' + n.lstrip('\\') for _, n in pe_insts]
        core_mod = {n: t for t, n in pe_insts}.get('u_array_core')
    if core_mod in mods:
        cells += ['u_pe/u_array_core/' + n.lstrip('\\') for _, n in instances(mods[core_mod])]
    area = None
    m = re.search(r'Total cell area:\s*([0-9.]+)', (a.syn_dir / 'area.rpt').read_text())
    if m:
        area = float(m[1])
    assert area, 'no Total cell area in area.rpt'
    side = math.sqrt(area / a.util) + 20.0
    lines = [f'# mock DB of {a.syn_dir}/{a.top}.syn.v (generated by netlist_mockdb.py)',
             f'set MOCK_TOP {a.top}',
             f'set MOCK_AREA_UM2 {area}',
             f'set MOCK_DIE_UM [list 0.0 0.0 {side:.3f} {side:.3f}]',
             'set MOCK_TERMS [list \\']
    lines += ['    ' + tcl_word(t) + ' \\' for t in terms]
    lines += [']', 'set MOCK_CELLS [list \\']
    lines += ['    ' + tcl_word(c) + ' \\' for c in cells]
    lines += [']']
    a.out.write_text('\n'.join(lines) + '\n')
    print(f'{a.out}: {len(terms)} terms, {len(cells)} cells (u_array_core module {core_mod}), '
          f'synthesized area {area:.1f} um2 -> estimated die {side:.2f} um square')


if __name__ == '__main__':
    main()
